# --------------------------------------------------------
# GhostG-X - WhatsApp Community & Support
# Developer: Professor / -ّ⸙𓆩ɢʜᴏꜱᴛɢ 𝐗 𓆪⸙-ّ
# --------------------------------------------------------

# Toutes les plateformes de don sont désactivées.
# Priorité : Communauté & Contact Direct.

github: []
custom: 
  -
# Canal Officiel: 'https://whatsapp.com/channel/0029VbCFj3oKbYMVXaqyHq3c' # Canal Officiel
  -
# Contacter le Développeur
 'https://wa.me/22651622652?text=Salut+Professeur,+j%27utilise+GhostG-X' 